name: Go

on:
  push:
    branches:
      - v2
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ['1.17.x']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          path: src/github.com/ikawaha/slackbot

      - name: Build
        run: go build -v ./...
        working-directory: src/github.com/ikawaha/slackbot

      - name: Test
        run: |
          go test -v ./...
        working-directory: src/github.com/ikawaha/slackbot
